### PR TITLE
Update idds-common to version 0.7.4

### PR DESCRIPTION
**Pull request by yesw2000**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by yesw2000** [comment]
@beckermr 

Please help merge this new version of **idds-common**.

Thanks,

**Comment by beckermr** [comment]
You should have write access here. Please accept the conda-forge invite and merge these PRs.

**Comment by yesw2000** [comment]
@beckermr ,

I saw the merge button on the PR for **panda-client**, but not on this PR for the package i**dds-common**. What could be wrong to prevent me from seeing the merge button?

**Comment by beckermr** [comment]
check now - sometimes the team permissions need updating like this: https://github.com/conda-forge/idds-common-feedstock/issues/6

**Pull request merged**
